### ISSUE TITLE
5/SWOT

### ISSUE THREAD

**Issue by alix2018** [alix2018/less-waste-vuejs#2]
**We want to** know what is our environment
**So that** we might be able to understand better our target
https://miro.com/app/board/o9J_l8bHJ6I=/?moveToWidget=3074457361840576637&cot=14

- [x] Forces
- [x] Faiblesses
- [x] Opportunité
- [x] Menaces

AC:
- [x] Partie de Shannon
- [x] Partie de Stéphanie

**Comment by sbaccus** [comment]
- [ ]  Politico-légal 
- [ ] economic
- [ ] social
- [ ] technologie
- [ ] ecologisch
- [ ] demographic
