### ISSUE TITLE
1/Définition du marché

### ISSUE THREAD

**Issue by alix2018** [alix2018/less-waste-vuejs#6]
**We want to** know on which market we are working
**So that** we know whom is sharing it with us

- [x] Generic Market
- [x] Product Market
- [x] Substitute Market

Miro: https://miro.com/app/board/o9J_l8bHJ6I=/?moveToWidget=3074457362275269189&cot=14

**Comment by sbaccus** [comment]
- [ ] Generic market
- [ ] Product market
- [ ] Substitute market
